---
# site settings
title: Prateek
subtitle: 
email: hi@prateekpunetha.dev
description: An Android and Linux Enthusiast 
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Prateek Punetha
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/PrateekPunetha
telegram_url: https://t.me/prateekpunetha
xda_url: https://forum.xda-developers.com/member.php?u=9362058
twitter_url: https://twitter.com/PrateekPunetha

# build settings
markdown: kramdown

sass:
  style: compressed

include: ["_pages"]
collections:
  pages:
    output: true
    permalink: :path

permalink: pretty
permalink: /:title/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
